/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/linkedin/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Linkedin Start
         * @description Redirects the user to LinkedIn's authorization page.
         *
         *     If user_id is provided, uses that user's saved LinkedIn credentials.
         *     Otherwise falls back to global env vars.
         */
        get: operations["linkedin_start_auth_linkedin_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/linkedin/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Linkedin Callback
         * @description Exchange code for token and redirect back to frontend.
         *
         *     Redirects to: {frontend_redirect}?linkedin_success=true&linkedin_urn=...
         *     Or on error: {frontend_redirect}?linkedin_success=false&error=...
         */
        get: operations["linkedin_callback_auth_linkedin_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Github Oauth Start
         * @description Start GitHub OAuth flow.
         *
         *     Redirects user to GitHub's authorization page.
         *     Requested scopes: read:user, repo (for private repo access)
         *
         *     Args:
         *         redirect_uri: Where to redirect after auth
         *         user_id: Clerk user ID (stored in state for callback)
         */
        get: operations["github_oauth_start_auth_github_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Github Oauth Callback
         * @description Handle GitHub OAuth callback.
         *
         *     Exchanges authorization code for access token and stores it encrypted.
         *
         *     Returns JSON status for the frontend callback component.
         */
        get: operations["github_oauth_callback_auth_github_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Auth
         * @description Check if user has valid LinkedIn connection
         */
        post: operations["refresh_auth_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Feedback
         * @description Submit user feedback (stored in SQLite and optionally emailed).
         */
        post: operations["submit_feedback_api_feedback_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/status/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feedback Status
         * @description Check if user has already submitted feedback.
         */
        get: operations["get_feedback_status_api_feedback_status__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/post/generate-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Preview
         * @description Generate an AI post preview from context.
         *
         *     Rate limited to 10 requests per hour per user to prevent abuse.
         *
         *     Supports multiple AI providers with tier enforcement:
         *     - Free tier: Always routes to Groq (fast, free)
         *     - Pro tier: Can choose groq, openai (GPT-4o), or anthropic (Claude 3.5)
         */
        post: operations["generate_preview_api_post_generate_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/post/generate-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Batch
         * @description Generate multiple posts for Bot Mode.
         *
         *     Takes a list of GitHub activities and generates posts for each one.
         *     Returns the list of generated posts with success/failure counts.
         *
         *     Supports tier-based model selection:
         *     - Free tier: Always Groq
         *     - Pro tier: Can specify groq, openai, or anthropic
         */
        post: operations["generate_batch_api_post_generate_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/post/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Providers
         * @description List available AI providers and their configuration status.
         *
         *     Returns provider availability based on configured API keys and user tier.
         *     Free tier users will see premium providers as unavailable for them.
         */
        get: operations["list_providers_api_post_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/post/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish
         * @description Publish a post to LinkedIn.
         */
        post: operations["publish_api_post_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle Clerk Webhook
         * @description Handle incoming Clerk webhook events.
         *
         *     Supported events:
         *     - user.deleted: Clean up all user data from databases
         *     - user.created: (logged only)
         *     - user.updated: (logged only)
         *
         *     Returns:
         *         200 OK on success (Clerk retries on non-2xx)
         */
        post: operations["handle_clerk_webhook_webhooks_clerk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Get user settings including persona.
         *
         *     Returns empty object if no settings exist yet.
         */
        get: operations["get_settings_api_settings__user_id__get"];
        put?: never;
        /**
         * Save Settings Path
         * @description Save user settings with user_id from path.
         *
         *     Used by PersonaSettings component.
         */
        post: operations["save_settings_path_api_settings__user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Settings Body
         * @description Save user settings from request body.
         *
         *     Uses user_id from request body.
         */
        post: operations["save_settings_body_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage
         * @description Get usage stats for the daily limit bar.
         *
         *     Returns posts used today out of daily limit (10 for free, 50 for pro).
         */
        get: operations["get_usage_api_usage__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Get dashboard stats for a user.
         *
         *     Returns post counts, credits, and growth metrics.
         */
        get: operations["get_stats_api_stats__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connection-status/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connection Status
         * @description Get connection status for LinkedIn and GitHub.
         *
         *     Returns which services are connected for this user.
         */
        get: operations["get_connection_status_api_connection_status__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Post
         * @description Create/save a new post record.
         */
        post: operations["create_post_api_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduled-posts/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scheduled Posts
         * @description Get scheduled posts for a user.
         */
        get: operations["get_scheduled_posts_api_scheduled_posts__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Image Preview
         * @description Get image suggestions for a post (uses Unsplash or similar).
         */
        post: operations["get_image_preview_api_image_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Templates
         * @description Get post templates.
         */
        get: operations["get_templates_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Posts History
         * @description Get post history for a user.
         */
        get: operations["get_posts_history_api_posts__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schedule Post
         * @description Schedule a post for later.
         */
        post: operations["schedule_post_api_scheduled_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduled/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scheduled
         * @description Get scheduled posts for a user.
         */
        get: operations["get_scheduled_api_scheduled__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduled/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Scheduled
         * @description Delete a scheduled post.
         */
        delete: operations["delete_scheduled_api_scheduled__post_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publish/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Full
         * @description Publish a post with optional image to LinkedIn.
         */
        post: operations["publish_full_api_publish_full_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Contact
         * @description Handle contact form submissions.
         */
        post: operations["submit_contact_api_contact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disconnect-github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect Github
         * @description Disconnect a user's GitHub OAuth token (secured - verifies ownership).
         */
        post: operations["disconnect_github_api_disconnect_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/github/activity/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Github Activity
         * @description Get GitHub activity for a user
         */
        get: operations["github_activity_api_github_activity__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/github/repo/{owner}/{repo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Github Repo
         * @description Get GitHub repository details
         */
        get: operations["github_repo_api_github_repo__owner___repo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/github/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Github Activity
         * @description Scan GitHub for recent activity (secured)
         *
         *     TIER RESTRICTIONS:
         *     - Free tier: Limited to 24-hour scan
         *     - Pro tier: Full customization
         */
        post: operations["scan_github_activity_api_github_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disconnect-linkedin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect Linkedin
         * @description Disconnect a user's LinkedIn account (secured - verifies ownership).
         *
         *     Removes the stored OAuth token, requiring re-authentication
         *     to post again.
         */
        post: operations["disconnect_linkedin_api_disconnect_linkedin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout
         * @description Create a Stripe Checkout session to start a subscription.
         *
         *     The user will be redirected to Stripe's hosted checkout page.
         *     After payment, they'll be redirected to success_url or cancel_url.
         *
         *     **Authentication Required**: Yes (Clerk JWT)
         *
         *     **Request Body**:
         *     - `user_id`: Clerk user ID
         *     - `price_id`: Stripe Price ID (from your Stripe Dashboard)
         *     - `email`: Optional customer email
         *     - `success_url`: Where to redirect after successful payment
         *     - `cancel_url`: Where to redirect if user cancels
         *
         *     **Response**:
         *     - `session_id`: Stripe session ID (for client-side redirect)
         *     - `checkout_url`: Direct URL to the checkout page
         */
        post: operations["create_checkout_api_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing-portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Portal
         * @description Create a Stripe Billing Portal session for subscription self-service.
         *
         *     Users can manage their subscription:
         *     - Update payment method
         *     - View invoices
         *     - Cancel subscription
         *
         *     **Authentication Required**: Yes (Clerk JWT)
         *
         *     **Request Body**:
         *     - `user_id`: Clerk user ID
         *     - `return_url`: Where to redirect after portal session
         *
         *     **Response**:
         *     - `portal_url`: URL to redirect user to
         */
        post: operations["create_portal_api_billing_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Subscription
         * @description Get current subscription status for a user.
         *
         *     **Authentication Required**: Yes (Clerk JWT)
         *
         *     **Request Body**:
         *     - `user_id`: Clerk user ID
         *
         *     **Response**:
         *     - `has_subscription`: Whether user has any subscription record
         *     - `status`: Subscription status (active, past_due, canceled, etc.)
         *     - `plan_id`: Stripe Price ID
         *     - `current_period_end`: Unix timestamp of current billing period end
         *     - `cancel_at_period_end`: Whether subscription is scheduled to cancel
         */
        post: operations["get_subscription_api_subscription_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Handle Stripe webhook events.
         *
         *     **Authentication**: None (signature verified internally)
         *
         *     This endpoint receives events from Stripe:
         *     - `checkout.session.completed`: User completed checkout
         *     - `invoice.payment_succeeded`: Recurring payment successful
         *     - `invoice.payment_failed`: Payment failed
         *     - `customer.subscription.updated`: Subscription changed
         *     - `customer.subscription.deleted`: Subscription canceled
         *
         *     **SECURITY**: Webhook signature is verified using STRIPE_WEBHOOK_SECRET.
         *     Never process events without verification.
         */
        post: operations["stripe_webhook_webhook_stripe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthRefreshRequest */
        AuthRefreshRequest: {
            /** User Id */
            user_id: string;
        };
        /**
         * BatchGenerateRequest
         * @description Request for batch post generation in Bot Mode.
         */
        BatchGenerateRequest: {
            /** User Id */
            user_id: string;
            /** Activities */
            activities: unknown[];
            /**
             * Style
             * @default standard
             */
            style: string | null;
            /**
             * Model
             * @default groq
             */
            model: string | null;
        };
        /**
         * BillingPortalRequest
         * @description Request to create a billing portal session.
         */
        BillingPortalRequest: {
            /** User Id */
            user_id: string;
            /**
             * Return Url
             * @default http://localhost:3000/settings
             */
            return_url: string;
        };
        /**
         * BillingPortalResponse
         * @description Response with billing portal URL.
         */
        BillingPortalResponse: {
            /** Portal Url */
            portal_url: string;
        };
        /**
         * CheckoutRequest
         * @description Request to create a checkout session.
         */
        CheckoutRequest: {
            /** User Id */
            user_id: string;
            /**
             * Price Id
             * @description Stripe Price ID (price_xxxxx)
             */
            price_id: string;
            /** Email */
            email?: string | null;
            /** Success Url */
            success_url?: string | null;
            /** Cancel Url */
            cancel_url?: string | null;
        };
        /**
         * CheckoutResponse
         * @description Response with checkout session details.
         */
        CheckoutResponse: {
            /** Session Id */
            session_id: string;
            /** Checkout Url */
            checkout_url: string;
        };
        /** ContactRequest */
        ContactRequest: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /**
             * Subject
             * @default General Inquiry
             */
            subject: string | null;
            /** Message */
            message: string;
        };
        /**
         * DisconnectRequest
         * @description Request model for disconnect endpoints (LinkedIn/GitHub).
         */
        DisconnectRequest: {
            /**
             * User Id
             * @description Clerk user ID
             */
            user_id: string;
        };
        /**
         * FeedbackRequest
         * @description Request model for feedback submission.
         */
        FeedbackRequest: {
            /** User Id */
            user_id: string;
            /** Rating */
            rating: number;
            /** Liked */
            liked?: string | null;
            /** Improvements */
            improvements: string;
            /** Suggestions */
            suggestions?: string | null;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /** User Id */
            user_id?: string | null;
            /**
             * Model
             * @default groq
             */
            model: string | null;
            /**
             * Style
             * @default standard
             */
            style: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImagePreviewRequest
         * @description Request model for image preview.
         */
        ImagePreviewRequest: {
            /** Post Content */
            post_content?: string | null;
            /** Query */
            query?: string | null;
            /** User Id */
            user_id?: string | null;
            /**
             * Count
             * @default 6
             */
            count: number | null;
        };
        /**
         * PostCreateRequest
         * @description Request model for creating a post.
         */
        PostCreateRequest: {
            /** User Id */
            user_id: string;
            /** Post Content */
            post_content: string;
            /**
             * Post Type
             * @default push
             */
            post_type: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @default draft
             */
            status: string | null;
        };
        /** PostRequest */
        PostRequest: {
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /**
             * Test Mode
             * @default true
             */
            test_mode: boolean | null;
            /** User Id */
            user_id?: string | null;
            /**
             * Model
             * @default groq
             */
            model: string | null;
        };
        /** PublishFullRequest */
        PublishFullRequest: {
            /** User Id */
            user_id: string;
            /** Post Content */
            post_content: string;
            /** Image Url */
            image_url?: string | null;
            /**
             * Test Mode
             * @default false
             */
            test_mode: boolean | null;
        };
        /**
         * ScanRequest
         * @description Request model for GitHub activity scanning.
         */
        ScanRequest: {
            /**
             * User Id
             * @description Clerk user ID
             */
            user_id: string;
            /**
             * Hours
             * @description Hours of activity to scan (1-720)
             * @default 24
             */
            hours: number;
            /**
             * Activity Type
             * @description Filter by specific activity type
             */
            activity_type?: ("push" | "PushEvent" | "pr" | "pull_request" | "PullRequestEvent" | "commit" | "CommitEvent" | "new_repo" | "CreateEvent" | "issue" | "IssuesEvent" | "comment" | "IssueCommentEvent" | "release" | "ReleaseEvent" | "fork" | "ForkEvent" | "star" | "WatchEvent" | "generic" | "milestone") | null;
        };
        /** ScheduleRequest */
        ScheduleRequest: {
            /** User Id */
            user_id: string;
            /** Post Content */
            post_content: string;
            /** Scheduled Time */
            scheduled_time: number;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string | null;
            /** Image Url */
            image_url?: string | null;
        };
        /**
         * SettingsRequest
         * @description Request model for saving settings.
         */
        SettingsRequest: {
            /** User Id */
            user_id?: string | null;
            /** Github Username */
            github_username?: string | null;
            /** Onboarding Complete */
            onboarding_complete?: boolean | null;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            } | null;
            /** Persona */
            persona?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SubscriptionStatusRequest
         * @description Request to get subscription status.
         */
        SubscriptionStatusRequest: {
            /** User Id */
            user_id: string;
        };
        /**
         * SubscriptionStatusResponse
         * @description Response with subscription details.
         */
        SubscriptionStatusResponse: {
            /** Has Subscription */
            has_subscription: boolean;
            /** Status */
            status?: string | null;
            /** Plan Id */
            plan_id?: string | null;
            /** Current Period End */
            current_period_end?: number | null;
            /**
             * Cancel At Period End
             * @default false
             */
            cancel_at_period_end: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    linkedin_start_auth_linkedin_start_get: {
        parameters: {
            query: {
                redirect_uri: string;
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    linkedin_callback_auth_linkedin_callback_get: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                redirect_uri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_oauth_start_auth_github_start_get: {
        parameters: {
            query: {
                redirect_uri: string;
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_oauth_callback_auth_github_callback_get: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                redirect_uri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_feedback_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_status_api_feedback_status__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_preview_api_post_generate_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_batch_api_post_generate_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_post_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    publish_api_post_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    handle_clerk_webhook_webhooks_clerk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_settings_api_settings__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_settings_path_api_settings__user_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_settings_body_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_api_usage__user_id__get: {
        parameters: {
            query?: {
                timezone?: string;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_status_api_connection_status__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scheduled_posts_api_scheduled_posts__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_preview_api_image_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_posts_history_api_posts__user_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_post_api_scheduled_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scheduled_api_scheduled__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scheduled_api_scheduled__post_id__delete: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_full_api_publish_full_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishFullRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_contact_api_contact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_github_api_disconnect_github_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisconnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_activity_api_github_activity__username__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_repo_api_github_repo__owner___repo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_github_activity_api_github_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_linkedin_api_disconnect_linkedin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisconnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_api_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_portal_api_billing_portal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingPortalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingPortalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_api_subscription_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_webhook_stripe_post: {
        parameters: {
            query?: never;
            header?: {
                "Stripe-Signature"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
