"""add_persona_to_user_settings

Revision ID: 88922ef82cf0
Revises: cdff07a73924
Create Date: 2025-12-28 21:49:38.452228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88922ef82cf0'
down_revision: Union[str, Sequence[str], None] = 'cdff07a73924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('feedback', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('post_history', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_post_history_user_id'), 'post_history', ['user_id'], unique=False)
    op.alter_column('scheduled_posts', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.create_unique_constraint('uq_scheduled_user_time', 'scheduled_posts', ['user_id', 'scheduled_time'])
    op.alter_column('tickets', 'id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('user_settings', sa.Column('persona', sa.Text(), nullable=True))
    op.alter_column('user_settings', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)
    op.drop_column('user_settings', 'persona')
    op.alter_column('tickets', 'id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_scheduled_user_time', 'scheduled_posts', type_='unique')
    op.alter_column('scheduled_posts', 'id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_post_history_user_id'), table_name='post_history')
    op.alter_column('post_history', 'id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)
    op.alter_column('feedback', 'id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)
    op.alter_column('accounts', 'id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
